version: '3.9'

x-restart-policy: &restart_policy
  restart: unless-stopped

x-host-config: &host_config
  environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:80

services:
  library-store-host:
    << : *restart_policy
    << : *host_config
    container_name: library_store_host
    image: library-store/host:latest
    build:
      context: .
      dockerfile: LibraryStore/Dockerfile
    depends_on:
      - postgres
    ports:
      - "4900:80"
    networks:
      - host_network
  
  employee-project-host:
    << : *restart_policy
    << : *host_config
    container_name: employee_project_host
    image: employee-project/host:latest
    build:
      context: .
      dockerfile: EmployeeProject/Dockerfile
    depends_on:
      - postgres
    ports:
      - "4901:80"
    networks:
      - host_network

  postgres:
    <<: *restart_policy
    container_name: ycidenis_postgres
    image: postgres:12.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=devdb
      - POSTGRES_PASSWORD=6VK4Vyg7yv8E
    command: [ "-c", "shared_buffers=512MB", "-c", "max_connections=500" ]
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - host_network

volumes:
  postgres_volume:
    name: ycidenis_postgres_volume

networks:
  host_network:
    name: ycidenis_network